name: shroom_calculator
description: "Calculadora Psilosofia es una aplicación que permite calcular dosis."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <3.8.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_screenutil: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: Iskoola Pota
      fonts:
        - asset: assets/fonts/IskoolaPotaRegular.ttf

